stages:
  - build

build-armv7:
  image: colemancda/meta-swift
  stage: build
  script:
    - export SRC_ROOT=$(pwd)
    - export MACHINE=beaglebone-yocto
    - export POKY_DIR=/tmp/poky
    - cd /tmp/
    - git clone --branch dunfell-23.0.20-cmake-3.22.3 https://github.com/MillerTechnologyPeru/poky.git
    - cd $SRC_ROOT
    - ./build.sh
  tags:
    - bastion-c5d.9xl

build-arm64:
  image: colemancda/meta-swift
  stage: build
  script:
    - export SRC_ROOT=$(pwd)
    - export MACHINE=qemuarm64
    - export POKY_DIR=/tmp/poky
    - cd /tmp/
    - git clone --branch dunfell-23.0.20-cmake-3.22.3 https://github.com/MillerTechnologyPeru/poky.git
    - cd $SRC_ROOT
    - ./build.sh
  tags:
    - bastion-c5d.9xl
